### ISSUE TITLE
Showing blank page after logging in

### ISSUE THREAD

**Issue by vpn1997** [Cloud-CV/Origami#100]
Node version: 9.2.1

npm version:5.5.1

Operating system:Ubuntu 17.04

Command line used:

Steps to reproduce:1.log in  with github account redirects to a blank page at http://localhost:8000/auth/social/signup/

**Comment by PalashTanejaPro** [comment]
Try rolling back you Node Js. 
Works on my Debian based system with Node v8.3.0

**Comment by vpn1997** [comment]
Hey i rolled back my node to version 8.3.0 ut still the problem persists ;(
![git](https://user-images.githubusercontent.com/17298412/34223423-5571da72-e5e5-11e7-9303-860204fe805b.gif)

**Comment by deshraj** [comment]
@vpn1997 do you see any error in the browser console? If yes, can you please share the error here?

**Comment by vpn1997** [comment]
@deshraj Nothing
![image](https://user-images.githubusercontent.com/17298412/34248368-cbc01646-e65b-11e7-9353-e8a310410813.png)

**Comment by vpn1997** [comment]
I think i found the solution.I created a superuser with same emailid as that of my github account.So when i changes that ,i was able to login without any problems. Allauth needs unique emailid i guess .
 
![image](https://user-images.githubusercontent.com/17298412/34250413-c76b3c40-e662-11e7-9914-4d8021bb4b07.png)
