### ISSUE TITLE
Minor UI Fix in the main website

### ISSUE THREAD

**Issue by gauravgrover95** [Cloud-CV/Origami#109]
Hi @tocttou , @deshraj 

#Minor UI fix on the home page of the [main website](http://origami.cloudcv.org/).

In my opinion, "_Out Projects Are Funded By_" is misspelled and it should be "_Our Projects Are Funded By_".

![screenshot 106 _li](https://user-images.githubusercontent.com/13467940/34416050-a3a1f8a2-ec17-11e7-9e79-fdcc1124685d.jpg)

Maybe the codebase is available [here](https://github.com/Cloud-CV/Origami/tree/master/Origami/src) as in the assets folder in the subdirectory ([here](https://github.com/Cloud-CV/Origami/tree/master/Origami/src)), I found all the images used on the homepage.

But while inspecting the website with DevTools, I found that _bundle.js_ the file was used to build the homepage and I am unable to find it in this repository. 

Can you please redirect me to the codebase?

**Comment by vpn1997** [comment]
@gauravgrover95 hey i think that website is yet to be updated and you can try to run this project on your local machine , webpack will automatically build bundle.js file. :smile:
