### ISSUE TITLE
Redirect to a blank page

### ISSUE THREAD

**Issue by vpn1997** [Cloud-CV/Origami#114]
Steps to reproduce:
1.Delete all the users present in the database using django admin panel.
2.Now create a superuser with same emailid as that of your github account.
3.Now try to login through your github account ,It will redirect you to a blank page.
p.s:for reproducing this issue you need to make your emailid public,
  
video (https://drive.google.com/file/d/1Jc5FuBF0P6208ioW-kfpBg7E3N0cTZXF/view)
  @AvaisP

**Comment by trexdinosaur** [comment]
Successfully repro'd. 

note: your email must be public for this to work!
