### ISSUE TITLE
AJAX network calls should not be in componentWillMount in react components.

### ISSUE THREAD

**Issue by fristonio** [Cloud-CV/Origami#126]
While working on issue #97 I found that in most of the code AJAX calls to the server are made in `componentWillMount`, while that should be avoided especially when we use `setState` in componentWillMount, here is an example.
https://github.com/Cloud-CV/Origami/blob/master/Origami/src/components/home/HomePage.js#L81
AJAX calls usually live in `componentDidMount`, not `componentWillMount`. The reason for that is that we don't want a call in an unmounted component, and when we do we are making an assumption that the data is not returned before the component mounts and setState is called.

We should port all the network related AJAX calls to `componentDidMount` from `componentWillMount`.

**I would like to work on this issue.**

**Comment by uttu357** [comment]
It would be great if you could file a PR regarding this issue.

**Comment by fristonio** [comment]
Ok, I will start working on it.
