### ISSUE TITLE
Default scroll in main layout.

### ISSUE THREAD

**Issue by fristonio** [Cloud-CV/Origami#129]
There is a default scroll in the main layout, due to height being `110vh` I don't know if it was intended, but I think we should not have that scroll. The footer should remain in the current view only, stuck to the bottom.

![image](https://user-images.githubusercontent.com/21292343/36315286-437e7276-135d-11e8-9998-b7d7cde20271.png)

**I would like to resolve this issue.**

**Comment by fristonio** [comment]
This would be a minor piece of work, In the App.js file we just need to make the height of the Layout 100vh rather than 110vh. There is no need for separate Pull Request for this. I will do it in any other UI fixes PR.

**Comment by uttu357** [comment]
@AvaisP What was the motivation behind changing the height to `110vh` in https://github.com/Cloud-CV/Origami/pull/62/files#diff-62a68ccfdd73e774263784a011e326aa?
