### ISSUE TITLE
Update package.json

### ISSUE THREAD

**Issue by fristonio** [Cloud-CV/Origami#132]
The current `package.json` file has many npm commands that do not work, I guess they were from a previous version of Origami and do not work with the current directory structure anymore. We should either update the package.json file or we should remove these scripts entirely.

![image](https://user-images.githubusercontent.com/21292343/36342918-53dacbb4-142b-11e8-8e4c-5f5b2795769b.png)

**I would like to work on this.**

**Comment by fristonio** [comment]
Here a few things I chalked out that needs refactoring in `package.json`

- [ ] Move prettier and eslint-plugin-prettier to dev dependencies from dependencies.
- [ ] Fix npm scripts to run origami in dev environment. Make `npm start`, `npm run dev` work.
- [ ] npm lint scripts do not work at all, the directory provided is not correct.

One thing that I don't understand is how is the current version of origami deployed, as it seems to me that no build script works, looking at the current package.json. So do we run origami in dev environment on the server too? If that is the case then we should definitely add build scripts to origami. So last peice of work would be. 

- [ ] Add build scripts to Origami

**Comment by uttu357** [comment]
Keep the test script. Once the tests are added it will be used. Add build scripts to Origami so that a node server is not required while running Origami in production. Make sure the docker scripts are not broken due to this.

**Comment by fristonio** [comment]
I have already added the build scripts to `package.json` and they work fine on my local environment. I will add the test scripts also.
