### ISSUE TITLE
No getting started page in current latest commit.

### ISSUE THREAD

**Issue by fristonio** [Cloud-CV/Origami#138]
There used to be a **getting started** page in origami ([See Here](http://origami.cloudcv.org/gettingstarted)). But it is missing in the current latest commit. In the current state, the **help** link in `initialSetup` points to getting_started but it gives a 404 error page since no getting started page exists.

We should have this page implemented as it shows the relevant steps needed to set up origami initially. As we will be needing to add a complete frontend for this, to temporary fix this we can link help to Origami **readthedocs.io**.

**Comment by fristonio** [comment]
One catch, the **Help** button on the sidebar links to Origami docs as of now. So to have a uniform behavior we should make both help options point to the same thing either to [docs](http://cloudcv-origami.readthedocs.io/en/latest/index.html) or to [getting started](http://cvfy.cloudcv.org/gettingstarted/configuration) page like this.

**Comment by uttu357** [comment]
Point Help everywhere to read the docs documentation for Origami.
