### ISSUE TITLE
Demo page UI is completely broken.

### ISSUE THREAD

**Issue by fristonio** [Cloud-CV/Origami#143]
Demo page UI is broken. Some of the things I noticed

- Not responsive
- Unnecessary scroll
- No proper alignment of components.
- Broken footer component.

[Demo Page UI screencast](https://www.useloom.com/share/422c9ed605134a8bbe20dab0018a2860)

**Comment by AvaisP** [comment]
Are you working on this @fristonio ?

**Comment by fristonio** [comment]
I think this depends on https://github.com/Cloud-CV/Origami/pull/133 will start working once it is merged. :)
