### ISSUE TITLE
[UI]: Background of MyDemos page does not seems to be correct.

### ISSUE THREAD

**Issue by fristonio** [Cloud-CV/Origami#150]
I don't think this was the intended background color of my demos page, I think it should be similar to Discover page as the two pages only differ in content.

**My Demos**

![image](https://user-images.githubusercontent.com/21292343/36898665-ce322e32-1e41-11e8-932a-13e2f70eb91a.png)

**Discover**

![image](https://user-images.githubusercontent.com/21292343/36898738-0a4ea8be-1e42-11e8-82b3-a59c46c894cf.png)

Please correct if I am wrong. :)

**Comment by vpn1997** [comment]
Hey @fristonio if you are working on this then please increase the gap between two adjacent rows in My demo page and make it similar to Discover page :smile: .

**Comment by fristonio** [comment]
Yeah, there are a lot of issues with the styling of the cards in my demo page, like the cards should be of even heights and should the wrap the description if it exceeds a given threshold. I will try to fix them all when I will go through this issue. You can mention the changes you need when I make a Pull Request for that. :)

**Comment by uttu357** [comment]
@fristonio Are you working on this?

**Comment by fristonio** [comment]
There are some other issues with the page as vipin mentioned I will gather them all and will make a Pull Request tomorrow :)

**Comment by vpn1997** [comment]
Closing as this issue wont be there as per new scheme of things.
