### ISSUE TITLE
[UI]: Redesign initial setup page

### ISSUE THREAD

**Issue by fristonio** [Cloud-CV/Origami#152]
The initial setup page UI is not in the best possible state, there are some styling issues with the form:
- The form inputs have unnecessary margins and paddings.
- A default scroll is present in the page which is not necessary.

![image](https://user-images.githubusercontent.com/21292343/36898972-1a49f128-1e43-11e8-8e1c-ed4ff365ac08.png)

**Comment by AvaisP** [comment]
Hey
Yes this page needs to be redesigned!

**Comment by fristonio** [comment]
Do we have a design for this page? I can do it if there is.

**Comment by AvaisP** [comment]
There isn't design. Please post a design here and get it approved. You can then develop it :D

**Comment by fristonio** [comment]
Sorry, @AvaisP I think I did not make my statement clear. What I meant was I can write the react code for the inital page frontend if there is a design available. Though I can work on design, but I think I would need some time for this because I don't have any experience with design as of now. Let's do it after we are done with other issues I have taken up earlier. In the meantime, if anyone else wants to work on this its open for a Pull Request. :)
