### ISSUE TITLE
[Discussion]: webpack-stats-local.json in the repository.

### ISSUE THREAD

**Issue by fristonio** [Cloud-CV/Origami#157]
Why do we have a `webpack-stats-local.json` in the repository, IMHO it should not be pushed to github.

- Remove webpack-stats-local.json
- add webpack-stats-local.json to gitignore

Inputs are welcome :)

**Comment by vpn1997** [comment]
I think we need webpack-stats-local.json file for travis builds. So it would be better if we rather not commit the file or add it to  .gitignore. :smile:

**Comment by fristonio** [comment]
I don't think its needed for Travis builds. It contains the stats about webpack compilation, but in our Travis build we don't even run webpack server. Only tests are run in Travis builds.
You can have a look at the contents of `webpack-stats-local.json` they are not at all required. webpack-stats-local.json is just for seeing stats about webpack compilation process on local build.

**Comment by vpn1997** [comment]
@fristonio go through this https://github.com/Cloud-CV/Origami/pull/113 . I once deleted that file in my commit and it caused problems in travis builds so thats why i told you not to delete that file.

**Comment by fristonio** [comment]
I don't understand why is it so :/ I would like to check the travis build errors that shows up when I remove webpack-stats-local.json. I will just make a test PR for this. Thanks for your input @vpn1997 :)

**Comment by fristonio** [comment]
The problem is that Django is decoupled with `django_webpack_loader` here
![image](https://user-images.githubusercontent.com/21292343/36937299-3a062b54-1f37-11e8-9a83-0e8bb762e3fc.png)

Essentially what should happen is wepack build should run in travis build which should automatically create `wepack-stats` file and then the bundles are used by django for various purposes like testing and all. But as of now no webpack-builds run on travis build, which leads to the failing of travis builds as django could not find a wepack STATS_FILE.

IMHO we should run a webpack build in travis as it would make sure that frontend build succeeds and there are no lint issues in Origami frontend. I am currently working on #145 Once I am done with adding the build scripts we can add a running webpack build to `travis.yml` which would remove this redundancy.

**Comment by fristonio** [comment]
Also one option that we have is since we don't use `django_webpack_loader` we can remove the dependency entirely. @AvaisP @uttu357 what's your stand on this?

**Comment by uttu357** [comment]
Fixed after #189.
