### ISSUE TITLE
[Discussion]:Invalid token creation

### ISSUE THREAD

**Issue by vpn1997** [Cloud-CV/Origami#167]
Current -Token created always starts with nongh and never with gh.
Ideal -Token initial should be 'nongh'  if the target is remote else it should be 'gh'.

Shouldnt checking on "webapp is running locally checkbox" ,change Token from nongh to gh ?

@AvaisP @uttu357 your thoughts .

**Comment by deshraj** [comment]
@vpn1997 I am not sure if I fully understand the issue. Can you please elaborate more on this?

**Comment by vpn1997** [comment]
Token created in the origami can either start with nongh or gh 
(as given in the origami lib)
![image](https://user-images.githubusercontent.com/17298412/37172591-47d79c6e-2337-11e8-9d8a-61e73ded0ca6.png)

But currently only  nongh tokens are being created
(register_page.js)

![image](https://user-images.githubusercontent.com/17298412/37172743-b11142d4-2337-11e8-890c-1f10663ba2ad.png)

Altho i am not exactly sure on what nongh or gh means but by reading origami-lib it seems that nongh means when target app is remote and gh for local.
Also we have webapp is running locally checkbox , so if my inference is true then by checking this checkbox should change token initials from nongh --> gh.

**Comment by AvaisP** [comment]
Hey 
nongh and gh were used earlier when Origami was going in a different direction. It's legacy code and you can feel free to drop both of them (it'll be a big task tho :) )
