### ISSUE TITLE
NGHDemoFramePage.js is Redundant 

### ISSUE THREAD

**Issue by vpn1997** [Cloud-CV/Origami#168]
NGHDemoFramePage component is never used or imported .
@AvaisP what purpose does NGHDemoFramePage serves?

**Comment by fristonio** [comment]
If you are talking about this class https://github.com/Cloud-CV/Origami/blob/master/Origami/src/components/deployment/UsePrebuiltProject/nghDemoFrame.js#L21 then it is imported and used here https://github.com/Cloud-CV/Origami/blob/master/Origami/src/routes.js#L23

**Comment by vpn1997** [comment]
Yup i missed that. Thanks @fristonio .Demoframe too redirects to blank page when no input and output component is provided (similar to #117 ).
