### ISSUE TITLE
[Discussion]:Use of DemoFrame

### ISSUE THREAD

**Issue by vpn1997** [Cloud-CV/Origami#174]
**Problem** -DemoFrame route which renders DemoFramePage  component is not hooked to any event or action(I may be wrong).
**Q**  - What is the use of DemoFrame and how can a user access the DemoFrame route ?

- **Any inputs are welcome**

**Comment by uttu357** [comment]
DemoFramePage can be only opened by link and is used to render the demo page embedded in an Iframe as in the main CloudCV website. It has all the styles from the Origami stylesheet removed and accepts stylesheet using PostMessageAPI from the parentWindow of the Iframe.
