### ISSUE TITLE
Make text input scrollable  

### ISSUE THREAD

**Issue by vpn1997** [Cloud-CV/Origami#181]
- Increase the height of the text input div and make it scroll able .

**Comment by uttu357** [comment]
Add it to the demo page UI issue #143.

**Comment by vpn1997** [comment]
@uttu357 hey it not demo page issue rather Text input component issue.Text input component will also be rendered in the drag and drop container. So i think it will be better if we create a separate PR related to this.I am not working on this issue as of now , so its open .

**Comment by uttu357** [comment]
@vpn1997 Okay sounds good! :+1:
