### ISSUE TITLE
[Bug]: Process.env object is not set properly

### ISSUE THREAD

**Issue by vpn1997** [Cloud-CV/Origami#183]
- CLIENT_IP & CLIENT_PORT is set to `undefined` in config.js because Process.env is not
  set  properly .

- Due to this `getWebAppStatus()` is not working properly which in turn shows the unreachable error in 
  the registration page .

**Comment by vpn1997** [comment]
- Hey dont you think we should add config.js file to .gitignore since we dont need to commit the changes 
 done in this file . Currently we have to provide  the value of CLIENT_PORT and CLIENT_IP as that of our origami.env file(which itself is in gitignore).

![screenshot](https://user-images.githubusercontent.com/17298412/37504678-0e3c10aa-2906-11e8-8f85-211b32bf262c.png)


@uttu357 @AvaisP

**Comment by vpn1997** [comment]
hey @AvaisP  was this issue there after merging (https://github.com/Cloud-CV/Origami/pull/105) ? 
Can any one conform if they are able to reproduce this issue :smile: .

**Comment by pavanagrawal123** [comment]
I don't recall this issue if the env is set properly. In retrospect: the proper way for #105 was to do process.env.x || x in order to not run into this issue.

**Comment by vpn1997** [comment]
Actually the main problem is we are trying to access the process env object at the client side .But process env is set at server side that's why its value is `undefined` on client side(config.js).We may have to revert #105 and modify `config.js` accordingly  .
@pavanagrawal123 @AvaisP

**Comment by uttu357** [comment]
@vpn1997 @pavanagrawal123 Just add it in the webpack config and then it will be available on the client side, like this https://github.com/Cloud-CV/CloudCV/blob/develop/frontend/webpack.config.dev.js#L5 and https://github.com/Cloud-CV/CloudCV/blob/develop/frontend/webpack.config.prod.js#L7

**Comment by pavanagrawal123** [comment]
I see, however, architecturally, isn't it a bad idea to expose our DropBox API key to client? When I originally wrote #105, I had thought that was only being run server side. If we expose the API key to client side, AFAIK, it can be abused and revoked.
