### ISSUE TITLE
[Discussion]:Providing Rest API to access models

### ISSUE THREAD

**Issue by vpn1997** [Cloud-CV/Origami#186]
Hey i am working on Providing API for accessing demo models. There is an issues i want to discuss 

-  Currently origami-lib requires socket-id in every request , without socket-id output functions wont work.
   But i don't think socket-id is a required parameter in the API calling.So i think there is some  modification 
   required in the origami-lib.
 
what are you views on this @AvaisP @uttu357

**Comment by vpn1997** [comment]
One way is that we create a function `isApi()` that return `True` if the request is made through api .
We can then return the Json data if its true otherwise use the output functions provided in the origami-lib.

**Comment by vpn1997** [comment]
One way  is that we provide a function `isApi()` that returns `True` if its an Api request otherwise `False`.
So the demo host user can return the json data if its true otherwise use normal output functions provided in the origami-lib.
@AvaisP @uttu357

**Comment by fristonio** [comment]
Fixed in https://github.com/Cloud-CV/origami-lib/pull/23
