### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by fristonio** [Cloud-CV/Origami#191]
The readme is not updated and setup will not work with the current Readme, as `node server.js` will fail the webpack config should be loaded with babel-node. We should replace `node server.js` with `yarn run dev` as it also runs lint tests in parallel. 

We can also add instruction to readme regarding setting up origami in the production build.

**Comment by uttu357** [comment]
Can you make the PR regarding the same as soon as possible?

**Comment by fristonio** [comment]
Yes I will make a PR in an hour or so. :)
