### ISSUE TITLE
[Discussion]: Profile page

### ISSUE THREAD

**Issue by fristonio** [Cloud-CV/Origami#193]
Currently there is only a slight difference between profile page and discover page. The profile page does not show any information regarding the user. I think we should use github api to get user profile and show it in profile page along with the demos created by the user.

**Profile Page**
![image](https://user-images.githubusercontent.com/21292343/37627123-04fd2b46-2bf9-11e8-9ae2-dfcb1949d637.png)

**Discover page**
![image](https://user-images.githubusercontent.com/21292343/37627144-1a94cfcc-2bf9-11e8-9912-6a345cf07046.png)

What are your thoughts on this @uttu357 @AvaisP

**Comment by uttu357** [comment]
@fristonio Before adding new features we should first focus on fixing the bugs present in Origami. Can you fix the issues you have created before working on this?

**Comment by fristonio** [comment]
Yeah, those issues are my top priority, but I post these issues so that I don't forget about them. :)
