### ISSUE TITLE
Some Issues and Suggestions

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/Origami#20]
- [x] On `/gettingstarted`,  if I scroll down and then press any of the navigation buttons on the left sidebar, then it should be loaded from the top of the page instead of showing the middle portion of the page. 
- [x] Create cvfy python package
- [x] Gist link missing on `/libdocs/registration`
- [ ] Add a link to one of the sample app that we have created
- [x] Porting cvfy documentation in sphinx would be more readable for users(since they are used to such format)

**Comment by tocttou** [comment]
Decoupling documentation from the app is a good step.
