### ISSUE TITLE
 Add footer in demo page.

### ISSUE THREAD

**Issue by vpn1997** [Cloud-CV/Origami#213]
- Currently demo page only shows footer when user is  **logged In**. 
- This issues deals with adding footer in demo page  when user is not logged in .

**Comment by alokpant** [comment]
@vpn1997 Is this issue still up for grabs? Can I take this issue?

**Comment by vpn1997** [comment]
@alokpant Hey !
We are currently revamping our whole fronted. So This issue wont be there in our new UI.
