### ISSUE TITLE
Add Pull request and issue templeates to comments.

### ISSUE THREAD

**Issue by fristonio** [Cloud-CV/Origami#219]
In reference to #120 and #121  where templates for GitHub pull request and issue are added.
For these templates, I propose that we should add them to comments rather than bare markdown. We can do that simply by adding enclosing templates in HTML comment signature **<!--** and **- ->**

**Comment by vpn1997** [comment]
We can also consider adding checklist for Pull request and Issue Template.

**Comment by fristonio** [comment]
My suggestion would be to keep it as minimal as it could be, making it complex won't be necessary IMHO.

**Comment by uttu357** [comment]
Closed by #221 and #222.
