### ISSUE TITLE
Typing error in Readme

### ISSUE THREAD

**Issue by geekayush** [Cloud-CV/Origami#232]
There's a typing error in "Contributing to Origami" section of the Readme.

## Expected Behavior
Make sure you run tests on your changes before you...

## Actual Behavior
Make sure your run tests on your changes before you...

## Screenshot
![screenshot_2018-09-22 cloud-cv origami](https://user-images.githubusercontent.com/22499864/45915512-a8f5d600-be73-11e8-98d3-b90da1b39350.png)

**Comment by fristonio** [comment]
@geekayush you can go ahead and make a Pull Request for this. :)

**Comment by geekayush** [comment]
@fristonio Sure
