### ISSUE TITLE
Add authentication to input component requests 

### ISSUE THREAD

**Issue by tocttou** [Cloud-CV/Origami#24]

**Comment by anweshknayak** [comment]
can I know where to start from ?

**Comment by tocttou** [comment]
Currently we do the output injection in the demos like this:

`Demo` --[input components][socketID: X]--> `Server` [processes input to produce output data] --[output data][socketID: X]--> `Demo` [puts output data into output components]

But this means that anyone who can get the socketID of the browser requesting the demo can inject any bogus data as well. This might not be an issue in reality ever, but it is a security flaw.

Take a look at:

1. [App.js](https://github.com/Cloud-CV/cvfy-frontend/blob/master/src/components/App.js#L31) to see how the sessionID (socketID) is created.

2. [distServer.js](https://github.com/Cloud-CV/cvfy-frontend/blob/master/server/distServer.js#L247) to see how a sessionID is stored and how the output data is [injected](https://github.com/Cloud-CV/cvfy-frontend/blob/master/server/distServer.js#L238).

3. [cvfy.py in cvfy-lib repo](https://github.com/Cloud-CV/cvfy-lib/blob/master/cvfy.py#L150) to see how data is injected in the demo applications.

You can think of what kind of authentication we should put in between and comment here.
