### ISSUE TITLE
Move to semantic-ui react package and drop jquery dependency

### ISSUE THREAD

**Issue by tocttou** [Cloud-CV/Origami#26]
Semantic UI has published official React bindings: http://react.semantic-ui.com/introduction
This can help us drop jquery dependency and reduce bundle size considerably.

**Comment by anweshknayak** [comment]
assign this to me.

**Comment by tocttou** [comment]
Its not a small update. You'll need to resolve #18 first.

**Comment by AvaisP** [comment]
We need to move to Antd now and not semantic-ui. I'll create a new issue to track that :smile:
