### ISSUE TITLE
Build a demo for Object Detection

### ISSUE THREAD

**Issue by dexter1691** [Cloud-CV/Origami#29]
Write a wrapper around the YOLO code to showcase the Object Detection algorithm:
https://github.com/thtrieu/darkflow

**Comment by anweshknayak** [comment]
@dexter1691 can I try ?

**Comment by deshraj** [comment]
@anweshknayak Sure. Let us know if you face any issue in setting up the project.

**Comment by anweshknayak** [comment]
@deshraj getting this error when trying to create a new app.

**Comment by anweshknayak** [comment]
One query. This is to be deployed "http://0.0.0.0:5001/". as given(for local deployment) . the respective changes to be made in outCalls/config.js ? @tocttou

**Comment by tocttou** [comment]
In the "Development mode": Yes
Note that you do not need development mode for this task. You may use the installation at: http://cvfy.cloudcv.org

**Comment by anweshknayak** [comment]
This issue is free. If anyone wants to do please proceed.

**Comment by AnshulMalik** [comment]
Hey! I working on it :)

**Comment by punarvasu510** [comment]
@AnshulMalik Are you still working on this issue?

**Comment by AnshulMalik** [comment]
Ahh, I have put this to hold for now.

**Comment by punarvasu510** [comment]
I'm working on this one.

**Comment by SudarAbisheck** [comment]
I completed it. 
How should I proceed from here on ??

![cvfy_yolo1](https://cloud.githubusercontent.com/assets/6151411/24286610/f22dae74-109b-11e7-84ef-b8384a3384a1.png)
![cvfy_yolo2](https://cloud.githubusercontent.com/assets/6151411/24286609/f21ac638-109b-11e7-992b-add30cf02f7e.png)

**Comment by tocttou** [comment]
Great. Now you should start working on your proposal ASAP. Make sure you mention this in it.

**Comment by tocttou** [comment]
@SudarAbisheck is it possible that you can make a docker image for this demo? We'd like to have a repository of easily install-able demos like this.

**Comment by tocttou** [comment]
The docker image should be usable like this:

`docker run -d -p 8000:8000 --env CVFY_TOKEN=<token> object-detection`

then we can use this demo running in a container with cvfy-frontend.

**Comment by SudarAbisheck** [comment]
Sure. I'll try to make a docker image.

**Comment by SudarAbisheck** [comment]
@tocttou I faced some problems while trying to dockerize the demos.
- Since you have to mention the ports the docker container will be exposing in the `Dockerfile`, now you have hardcode the port number, the demo flask server will be using. And once you do that, the `CVFY_TOKEN` lost half of its purpose. You could still use a custom port, but have to pass it as an argument while starting the container
- When running the demo as a docker container in the local environment, the IP address of the cvfy-frontend server passed through the `CVFY_TOKEN`, which is `0.0.0.0`, can't be used anymore to connect to the cvfy-frontend from inside the docker container. In this case, we either have to use docker networks or docker-compose to run the demos along with cvfy-frontend.

**Comment by tocttou** [comment]
@SudarAbisheck 

Both of these problems (although the first one is not really a problem) can be solved by running the container as following:

`docker run -d --net=host --env CVFY_TOKEN=<token> object-detection`

by making the container inherit the host's network.

**Comment by tocttou** [comment]
@SudarAbisheck it would be great if you can [push the image to Dockerhub](https://docs.docker.com/engine/getstarted/step_six/) as well, so  that we can just do:

`docker run -d --net=host --env CVFY_TOKEN=<token> sudarabisheck/object-detection` without building the image ourselves (do provide the Dockerfile and other required files separately though).

**Comment by SudarAbisheck** [comment]
I completed it. I pushed the container to docker hub. 
The github repo: https://github.com/SudarAbisheck/cvfy-object-detection

**Comment by tocttou** [comment]
@SudarAbisheck nice work! 😄 Please mention this in your proposal.

**Comment by tocttou** [comment]
@SudarAbisheck you have hardcoded the token in your demo. I was able to run it using: `docker run --net=host --env CVFY_TOKEN=<TOKEN> sudarabisheck/object-detection` but after fixing the port in cvfy-frontend to `8000` specifically. Works fine. Thanks!

**Comment by SudarAbisheck** [comment]
@tocttou I have fixed it. Now you have to run the demo using the command
```
docker run -d --net=host --env CVFY_TOKEN=<TOKEN> sudarabisheck/object-detection
```
and the demo runs on the port given through the token.

**Comment by tocttou** [comment]
Great! Thanks.
