### ISSUE TITLE
Build a demo for VQA

### ISSUE THREAD

**Issue by dexter1691** [Cloud-CV/Origami#31]
Build a demo for VQA using the following code:
https://github.com/JamesChuanggg/VQA-tensorflow

**Comment by uttu357** [comment]
@dexter1691 I am interested in working on this task. :)

**Comment by uttu357** [comment]
Would like to try building a demo for this.. :)

**Comment by deshraj** [comment]
@uttu357 Sure. Let us know if you need some help with this.

**Comment by dexter1691** [comment]
@uttu357 : For VQA, here is one thing you need to take care of
People can ask multiple questions for the same image. The way the code works, you don't necessarily need to extract features for the image again and again. Once the features are extracted, you can reuse those for different questions. 

Don't think this feature exists right now in the cvfy. While you are working on it, think about how to reuse the features of an image for that session. 

We should have the ability to reuse the features, and give users the choice to specify if some intermediate output can be cached for a session.

**Comment by uttu357** [comment]
Sure! I will try to implement it.. :+1:

**Comment by deshraj** [comment]
@uttu357 any update on this?

**Comment by alasin** [comment]
@deshraj @dexter1691 Is it still open? Can I work on it?

**Comment by deshraj** [comment]
@alasin yeah it is still open. Please go ahead if you are interested.

**Comment by alasin** [comment]
@deshraj Couldn't get a pre-trained model for the code in 
https://github.com/JamesChuanggg/VQA-tensorflow, so got a demo working that's based on this code:
https://github.com/paarthneekhara/neural-vqa-tensorflow

![scr_cat](https://user-images.githubusercontent.com/2655401/27299418-f92a9cbc-5549-11e7-8a6f-6194d62791ff.png)

The demo reuses the extracted image features by maintaining a dictionary with a MD5 hash of the image as key and image features as value. The image features are then passed on to the inference code.

Here's my forked off repo from original code:
https://github.com/alasin/neural-vqa-tensorflow

Let me know how to submit a PR for this or if any changes are required.

**Comment by alasin** [comment]
@deshraj @dexter1691 Awaiting your inputs.

**Comment by vpn1997** [comment]
can i take this issue ? @uttu357 @deshraj ?
