### ISSUE TITLE
Build a demo for Grad-CAM

### ISSUE THREAD

**Issue by dexter1691** [Cloud-CV/Origami#32]
Build a demo for Grad-CAM by writing a wrapper around this code:
https://github.com/jacobgil/keras-grad-cam

**Comment by uttu357** [comment]
@dexter1691 I would like to work on this.

**Comment by dexter1691** [comment]
Awesome! Please go ahead! Let us know if you get stuck

**Comment by dexter1691** [comment]
This might not end up being trivial. VQA would have been an easier choice! 
But this one definitely will be more fun.

**Comment by uttu357** [comment]
Sure ill try to complete it asap.. :+1:

**Comment by uttu357** [comment]
@dexter1691 I have constructed the wrapper for Grad-CAM https://github.com/uttu357/keras-grad-cam/tree/cvfy-wrapper. Currently attempting to dockerize the application.

**Comment by uttu357** [comment]
Successfully dockerized the application. The wrapper is ready and can be run from a docker container.
https://github.com/uttu357/keras-grad-cam/tree/cvfy-wrapper

**Comment by deshraj** [comment]
@uttu357 This looks great. :) 

Feel free to pick other issues if you are interested. I will try to find sometime and get this up on the main CVFY app.
