### ISSUE TITLE
Save Results into Dropbox

### ISSUE THREAD

**Issue by dexter1691** [Cloud-CV/Origami#35]
Right now results are only displayed in browser. 

We should allow easy download of these results either into Google Drive / Dropbox or download a compressed file containing all the output in the session.

**Comment by AvaisP** [comment]
Hey @dexter1691 ,
I'd like to implement this feature.

**Comment by AvaisP** [comment]
How should we implement the flow? Will this come in cvfy-lib or in cvfy-frontend? I was thinking of having it in cvfy-lib such that the demo creator can provide the user the option whether they want to save the results to their dropbox or not. The user can choose to save it by clicking on the save button which would then call the saveToDropBox() function. Sounds good?

**Comment by tocttou** [comment]
@AvaisP No. SaveToDropbox should be implemented in the frontend entirely. cvfy-lib is solely meant to be used to by the project creator to interface with the project only.

**Comment by AvaisP** [comment]
@tocttou Cool. I will look into it and get it done ASAP. On a side note, Is there a document that explains the project structure? If there isn't then I'd like to help create one so that new contributors can dive right into development!

**Comment by tocttou** [comment]
The structure is the same as any redux application out there. Anyone who has worked with redux before will find it all easy to navigate and understand. If you haven't, this is a nice place to start: https://marmelab.com/blog/2015/12/17/react-directory-structure.html

**Comment by AvaisP** [comment]
@tocttou
Thank you so much! Working on it!

**Comment by AvaisP** [comment]
@tocttou @dexter1691 
So I've created a dropbox uploader https://github.com/AvaisP/react-dropbox-saver/blob/master/react-dropbox-saver.js . Now the issue I am facing is that it accepts a url to the image as in input. Instead in our app, we are using a base64 image. Any tips on how to tackle this ?

**Comment by AvaisP** [comment]
I was thinking of writing it to a .png file on the server, followed by giving the path as an input to the saver and then finally deleting the .png file from the server. But there has to be a better way :see_no_evil:

**Comment by dexter1691** [comment]
@AvaisP: Do you mean to say that to save a file in Dropbox, the only way is to give it a URL? 
This sounds okay to me, right? What do you think will be a better way?

**Comment by AvaisP** [comment]
@dexter1691  Yes. I am currently trying to convert the base64 data to a blob. I'll then create a URL using URL.createObjectURL(). I hope this will works. If it doesn't then as a last resort I'll just save it on the server, upload and then delete!

**Comment by AvaisP** [comment]
@dexter1691  None of the two approaches work. Can you suggest another way?
