### ISSUE TITLE
Sample media input 

### ISSUE THREAD

**Issue by dexter1691** [Cloud-CV/Origami#36]
For people to quickly try the model on the demo page, we should allow the author of that demo to choose a few sample input media (can be an audio file / image / video / text etc) that would show up on the page. 

For ex: http://cloudcv.org/vqa/

**Comment by In-vincible** [comment]
Hey @dexter1691, I would to work  on this issue, since I am new to this project can you help me where to start

**Comment by dexter1691** [comment]
Hi @In-vincible: The feature requires using standard gallery components. We use react and material design so find standard open source components that we can use for gallery. 
You are supposed to give the ability to choose between different styles
1.) Image Gallery to choose from
2.) Sample Videos
3.) Sample Audio

Right now 1.) is very high priority. Other two are not. So I suggest start with 1.)

**Comment by In-vincible** [comment]
@dexter1691 right now there are 6 images shown on the demo page, users are able to choose one at a time, so am I supposed to allow them to select multiple at a time?..sorry I was unable to understand the task properly. though I have looked out for gallery components in react and material as far as front end goes.

**Comment by In-vincible** [comment]
@dexter1691 please help me get started with issue a little bit, right now I am not familiar with the code base.

**Comment by dexter1691** [comment]
@In-vincible The task is to implement the same functionality in this project. You need to replicate the gallery like feature in the CloudCV demo for cvfy-frontend. Does that make sense?

**Comment by In-vincible** [comment]
yeah, really sorry took extra time :)

**Comment by AvaisP** [comment]
#62 Solves this. Closing the issue
