### ISSUE TITLE
Small Typo on the website

### ISSUE THREAD

**Issue by daminisatya** [Cloud-CV/Origami#39]
![image](https://cloud.githubusercontent.com/assets/6227784/25798797/2a82720a-3400-11e7-9886-6a2baf65ecf6.png)

This can be a beginner's issue :)

**Comment by AvaisP** [comment]
@daminisatya Are you working on this right now? :smile:

**Comment by daminisatya** [comment]
@AvaisP Nope I'm not but i can send a PR if it is ok. :)

**Comment by deshraj** [comment]
@daminisatya you are most welcome to submit PRs. :)

**Comment by AvaisP** [comment]
The home page has been redesigned to use Ant Design. Closing this
