### ISSUE TITLE
Change create demo UI

### ISSUE THREAD

**Issue by AvaisP** [Cloud-CV/Origami#78]
Update the demo creation UI to allow users to create demos using drag and drop

**Comment by vpn1997** [comment]
Hey i want to work on this, can you give detailed explanation on what to do. :smile: @AvaisP

**Comment by AvaisP** [comment]
@vpn1997 

Current state: 
Users go to the input/output component page, select N copies of the same type of component and click on save. They have to return to the page to add a different type of component. They can view the preview the entire input/output section in the dialogue box when they press preview.
Goal state:
Users should be able to drag any input component into a seperate div at the end of the input components page. The same should be done for output components. The users should be able to drag and drop as many copies of a component as they need. If there are more than one type of components being used, the user should be able to mix them without having to come back to the components page.

**Comment by vpn1997** [comment]
@AvaisP Hey few questions. 
1.What to do with modify,preview and save button .
2.Do we need to show anything in the separate div in which components are being dragged and dropped.
3.Currently Origami only supports one type of output component.Do we need to change that ?

**Comment by AvaisP** [comment]
@vpn1997  
1. Do away with the modify and preview buttons. The save button should save the entire demo. 
2. Yes. It needs to display the preview of the demo page. In fact, it needs to allow components to be removed from the demo page (by dragging a component out of the div)
3. What do you mean? 

Yes what you're thinking is very close to what we want! :D

**Comment by vpn1997** [comment]
Hey my initial attempt.

![gf](https://user-images.githubusercontent.com/17298412/36060586-b0d0d67e-0e72-11e8-87b6-6cdef58c7a8b.gif)

**Comment by AvaisP** [comment]
@vpn1997 This is a great start! :D 
Instead of displaying the component names(eg. Text Input, Image Input) after dropping it in the div, render the component in the div itself. Basically, the div should serve as a preview for the demo creator. 

Also, instead of always having the component be placed below the previously entered component, allow users to place the components above and on either side of the components already present!

**Comment by AvaisP** [comment]
Hey
This is good. We need only one Send button though. In your video there is a send button for every input component. Also, I saw that a component was going out of the drag and drop div(0:33). Please fix that as well! :smile:

**Comment by vpn1997** [comment]
hey @AvaisP  have a look
https://drive.google.com/file/d/1urtnZzS6NuADri5Yk8N2diTvt4f9nnQP/view

About drag and drop , i tried to minimise the portion of the element getting out of the div (now only 10% of the length of the element can be outside scroll div).We can minimise that to 0 % but then we have to compromise with the size of the elements in the div(like reducing the size of graphs and charts) :smile: 

P.s Ignore the comma trails and label button is yet to be added

**Comment by AvaisP** [comment]
Excellent work @vpn1997. Currently we only allow the user to place new components above or below another component. Please allow users to place components on the left/right of a previously placed component as well.

**Comment by vpn1997** [comment]
hey @AvaisP sortable component can be either in x axis or y axis . Sorting in both the axis is bit difficult and i don't think it will serve much purpose  .But if its a necessary feature then i can try to find a workaround for it. :smile:

**Comment by vpn1997** [comment]
Hey @AvaisP i am done with the drag and drop part except part of allowing user to place component left /right  feature  with will require whole lot of modification . Should i submit a PR ?

**Comment by AvaisP** [comment]
Yes please submit a PR!
