### ISSUE TITLE
Build a demo for EAST

### ISSUE THREAD

**Issue by dexter1691** [Cloud-CV/Origami#83]
https://github.com/argman/EAST

This is an implementation for EAST: An Efficient and Accurate Scene Text Detector.
It's based on Tensorflow and has a clean / easy to deploy code for text detection. 

Given our current input / output methods, this seems like a pretty easy demo to host. 

Also, the repository links to a demo that has been down for a while. Will be nice to host it and then send a PR to the original repository with an updated link for demo. :)

**Comment by radonys** [comment]
I am currently working on it. The demo for EAST is running on localhost and I will host using CVFY shortly.

**Comment by radonys** [comment]
The link has been hosted.

Link: http://cvfy.cloudcv.org/p/1a2o27622

Changes made for implementation:

1. Modified [_run_demo_server.py_](https://github.com/radonys/EAST/blob/master/run_demo_server.py) to support Origami.
2. Modified [_origami.py_](https://github.com/radonys/EAST/blob/master/origami.py) to support _python3_ as the original code for EAST Implementation was written in Python 3.

Before making any PR, should I make any changes like in the README.md, mentioning about this organization and changes made in the codebase?

Note: Currently the server is running on my institute's GPU server. So, it will be a temporary hosting.

**Comment by uttu357** [comment]
Can you dockerize the demo so that deployment of the demo is easy. We'd like to have a repository of easily install-able demos like this. The docker image should be usable like this:
`docker run -d --net=host --env CVFY_TOKEN=<token> east-detector`
then we can use this demo running in a container with cvfy-frontend.

**Comment by uttu357** [comment]
Also currently I cannot receive a response from the demo. Probably the demo is down.

**Comment by Rish1997** [comment]
Hey @dexter1691 !! could I work on this issue??
