### ISSUE TITLE
Typo error in Homepage

### ISSUE THREAD

**Issue by HargovindArora** [Cloud-CV/Origami#84]
![origami](https://user-images.githubusercontent.com/22341493/31808809-696c4342-b592-11e7-9d3f-1195d8e631a6.png)

Here it is written, "Out Projects Are Funded By".
Rather it should be "Our Projects are Funded by".
Please have a look. @dexter1691 :)

**Comment by deshraj** [comment]
@HargovindArora feel free to fix this and send a pull request.

**Comment by HargovindArora** [comment]
@deshraj I searched a lot and was unable to find the required file where the change has to be made. Please, can you guide? :)

**Comment by AvaisP** [comment]
@HargovindArora This is the Old UI. The app has since been changed and will be hosted soon.

**Comment by HargovindArora** [comment]
@AvaisP you mean that this error will be resolved on it's own and there is nothing to be changed. Right?

**Comment by AvaisP** [comment]
Yes it has been resolved! Try working on some other issue :smile:

**Comment by HargovindArora** [comment]
Ohkay. Got it. Thanks :)
