### ISSUE TITLE
Updating react-router to v4 leads to breaking changes

### ISSUE THREAD

**Issue by owenl131** [Cloud-CV/Origami#97]
Npm package react-router-dom needs to be added, for react-router to be upgraded to v4. Code needs to be rewritten as well as react-router v4 is a complete rewrite from react-router v3. Recommended to look through https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/migrating.md

One error message is: 
> Warning: Failed prop type: The prop `history` is marked as required in `Router`, but its value is `undefined`. in Router

Node version: v8.9.1

npm version: 5.5.1

Operating system: ubuntu 16.04

**Comment by fristonio** [comment]
Hey, I would like to work on this issue if no one is assigned to it.
